import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated automatically from the docs folder structure.
 * Numeric prefixes on folders (00-, 01-, ...) determine ordering.
 * Everything lives under a single top-level "Roadmap" category.
 */
const sidebars: SidebarsConfig = {
  roadmapSidebar: [
    {
      type: 'category',
      label: 'Roadmap',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '.'}],
    },
  ],
};

export default sidebars;
